### ISSUE TITLE
gst-home-audio build issue and error is related to meson subproject

### ISSUE THREAD

**Issue by bhoomil-avch** [DolbyLaboratories/gst-home-audio#1]
![gst-home-audio-build-error](https://user-images.githubusercontent.com/6021881/103146502-80569800-4770-11eb-82c2-c5e9eb43c018.png)

**Comment by Bhoomil-Chavda-Einfochips** [comment]
can somebody please reply me on this issue?

**Comment by txndr** [comment]
Thanks for reporting. What you see is expected if running this repository without source code for proprietary libraries. These are delivered by Dolby as a separate software kit. If meson doesn't detect the source code for subprojects it builds shim layer instead.
